name: hit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - zarr
  - fsspec
  - gcsfs
  - aiohttp
  - geopandas
  - shapely
  - fiona
  - rasterio
  - rioxarray
  - rasterstats
  - duckdb
  - requests
  - xclim>=0.52
  - matplotlib
  - mercantile
  - pillow
  - pip
  - pip:
    - plotly
    - streamlit
    - fastapi
    - "uvicorn[standard]"
    - bottleneck
    - -e vendor/target_py
    - -e .
